# Generated by Django 4.0.2 on 2022-02-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[(1, 'Я приду / Мы приедем'), (2, 'Буду со своей парой'), (3, 'Не смогу прийти')], max_length=1, verbose_name='Присутствие')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('surname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('housing', models.BooleanField(default=False, verbose_name='Наличие жилья')),
                ('drink', models.CharField(choices=[(1, 'Вино'), (2, 'Шампанское'), (3, 'Водка'), (4, 'Коньяк'), (5, 'Виски')], max_length=1, verbose_name='Напитки')),
                ('date_submit', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
    ]
