# Generated by Django 4.0.2 on 2022-02-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='weddingdata',
            name='drink',
        ),
        migrations.AlterField(
            model_name='weddingdata',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wedding.attendance', verbose_name='Присутствие'),
        ),
        migrations.AddField(
            model_name='weddingdata',
            name='drink',
            field=models.ManyToManyField(to='wedding.Drinks', verbose_name='Напитки'),
        ),
    ]
