# Generated by Django 4.0.2 on 2022-02-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_attendance_drinks_remove_weddingdata_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='to_be',
            field=models.CharField(max_length=30, verbose_name='Присутствие'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='drink',
            field=models.CharField(max_length=15, verbose_name='Напитки'),
        ),
        migrations.AlterField(
            model_name='weddingdata',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wedding.attendance', verbose_name='Напитки'),
        ),
        migrations.AlterField(
            model_name='weddingdata',
            name='drink',
            field=models.ManyToManyField(blank=True, to='wedding.Drinks', verbose_name='Присутствие'),
        ),
    ]
