# Generated by Django 4.0.2 on 2022-02-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_alter_attendance_to_be_alter_drinks_drink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingdata',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wedding.attendance', verbose_name='Напитки'),
        ),
    ]
