# Generated by Django 4.0.2 on 2022-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0004_alter_weddingdata_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingdata',
            name='drink',
            field=models.ManyToManyField(blank=True, to='wedding.Drinks', verbose_name='Предпочтения по напиткам'),
        ),
    ]
